import "./globals.css";
import { ModalContextProvider } from "./context/ModalContext";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalContextProvider>
          {props.modal}
          {props.children}
        </ModalContextProvider>
      </body>
    </html>
  );
}
