export const ProjectsInfo = {
  "price-performance-scraper": {
    name: "Price-Performance Scraper",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Price-Performance Scraper Description</p>
    ),
    cssId: "project-pps",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: [
      "Python",
      "Django",
      "HTML",
      "CSS",
      "TypeScript",
      "React",
      "Next.js",
      "PostgreSQL",
      "Docker",
    ],
    thumbnailImgSrc: "/images/pps-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB4QAAICAQUBAAAAAAAAAAAAAAIEAQMRBQYHEhMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwX/xAAhEQABBAEDBQAAAAAAAAAAAAABAgQRITEAElEDBRMiQf/aAAwDAQACEQMRAD8AOQLdk8wutO8ibc1Ft9dHXbKGF9a8q64oRCxUIr8pjAXdjP7mwSgcjjtMxw5eSFhSbKJ9R9JBxAsYqs3pW3a0Mel4t0gbuRYubJ5xr//Z",
    previewImgSrcList: [
      "/images/pps-preview-1.png",
      "/images/pps-preview-2.png",
      "/images/pps-preview-3.png",
      "/images/pps-preview-4.png",
      "/images/pps-preview-5.png",
    ],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EABwQAAMAAgMBAAAAAAAAAAAAAAECBAMFBgcRIf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAgEQACAQMFAQEAAAAAAAAAAAABAhEEBUEAAxIhMQZx/9oADAMBAAIRAxEAPwABdwcH0+tz7ZOVZKNldr03MslcdLxIjTwQ5p3OJGZWCtnyeqfrggFvAACae6VtyVN9mieMiAepYEY9gfmmV+Xp7VSlUeQDuYjtArT7nlEYjX//2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB4QAAEEAQUAAAAAAAAAAAAAAAQBAgMSIQAFBhEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAbEQABBQEBAAAAAAAAAAAAAAABAAIDBBESwf/aAAwDAQACEQMRAD8AKfkZhZu7zOKKkfWWjLL41I8JjrQ2ZrDQ+Q6c9U468VdvEYwL/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAIABAcAAAAAAAAAAAAAAAEDAgQFEQAGBxQhUYH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EACMRAAEDAwIHAAAAAAAAAAAAAAECAxEEBTEAEhMhIkFCgcH/2gAMAwEAAhEDEQA/ADH1IlqanN9U2FMTLrgQiJaljiAlSrkX7JJ9wj1S1WL4zbYQFeIwO3ydU3G2qs9e5Rlwr2R1ERMgKxzxMetf/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB4QAAIBAwUAAAAAAAAAAAAAAAECAwAEIQUGEWGB/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABoRAQEAAgMAAAAAAAAAAAAAAAIBAAMRIWH/2gAMAwEAAhEDEQA/ACy3uk14LTVbqRGlnj5kcRBSzAnJI6x5RvY9jqV5uFE9ZhPUnmf/2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB4QAAIBAwUAAAAAAAAAAAAAAAECIQMEBQAGERVx/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABgRAAMBAQAAAAAAAAAAAAAAAAECEQAS/9oADAMBAAIRAxEAPwAg8luvsr17xscKbtCqtUlUjiAwMek6bN01xAgm/9k=",
    ],
    // cssGradient: "bg-gradient-to-r from-violet-500 via-rose-500 to-orange-600",
  },
  "pathfinding-race": {
    name: "Pathfinding Race",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Pathfinding Race Description</p>
    ),
    cssId: "project-pathfinding",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["HTML", "CSS", "JavaScript", "React"],
    thumbnailImgSrc: "/images/pathfinding-race-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EACAQAAICAQMFAAAAAAAAAAAAAAECAwQGBQcRABIhI0H/xAAVAQEBAAAAAAAAAAAAAAAAAAACBv/EACARAAIBAwUBAQAAAAAAAAAAAAECEQMEEgAFITEyBkH/2gAMAwEAAhEDEQA/AE3cDPsj2pzLTcX0d61mtZkpKstmv7oo5ZUR1DKQCe1/DEcgj7z0vldjsN2pM7AqAKxgR6p5EHryY5WJ5nLVbttlaXFKqkFWDMRiQFAFJXjEgmciecuj1+6//9k=",
    previewImgSrcList: [
      "/images/pathfinding-race-preview-1.png",
      "/images/pathfinding-race-preview-2.png",
      "/images/pathfinding-race-preview-3.png",
      "/images/pathfinding-race-preview-4.png",
      "/images/pathfinding-race-preview-gif.gif",
    ],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EAB4QAAIDAAEFAAAAAAAAAAAAAAECAwQhBQYREmKR/8QAFAEBAAAAAAAAAAAAAAAAAAAABv/EAB0RAAIBBAMAAAAAAAAAAAAAAAECAAMEESExscH/2gAMAwEAAhEDEQA/AHngbSV+m3rwQBYqEq11QNsgaIazHc8Se3t9N13AVmI2c9RQwc3ezy3s/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EAB0QAAICAgMBAAAAAAAAAAAAAAECAwQFEQAGEiH/xAAUAQEAAAAAAAAAAAAAAAAAAAAG/8QAHhEBAAMAAgIDAAAAAAAAAAAAAQIDEQQSAEEhIlH/2gAMAwEAAhEDEQA/AG+x1XIQXccuA7LNQroYI5qiwJIkqiMu42w9KGA8kA/N7HD3Hur4vFuL6o2Tl3YuMSJLc0F7Tj6loPuD4tqI18t2IxZP6JJwERwB+WPVV37Z5//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACQQAAADBgcBAAAAAAAAAAAAAAEEEQIDBQYSFAAHCBMjJEEy/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABwRAAIBBQEAAAAAAAAAAAAAAAECAAMSITGBwf/aAAwDAQACEQMRAD8AGhs9SCV0+hBneUxC6bkxovfcCg8AoDG8HXqVRq+1X33AtQszEk6jeL++z//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EACEQAAAGAgEFAAAAAAAAAAAAAAECAwQREgYHAAUWISJh/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABsRAAIBBQAAAAAAAAAAAAAAAAERAAIDImHB/9oADAMBAAIRAxEAPwAutM6xQmLJa2LqboxXoMjl7lIu5B3YKnvUVBTmPWKxH3zwys4kxRu6t9n/2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EAB8QAAICAgEFAAAAAAAAAAAAAAECAxEEBgAVITFRcf/EABQBAQAAAAAAAAAAAAAAAAAAAAb/xAAdEQACAgEFAAAAAAAAAAAAAAABAgADBBFCUaHB/9oADAMBAAIRAxEAPwB51LEmxdYgx1nRo+kvKFeBSQUoVfnuG+ggV64dvddGcjk9RcanbJJLbvZ//9k=",
    ],
    // cssGradient: "bg-gradient-to-r from-yellow-300 to-pink-600",
  },
  "paint-a-wave-function-collapse": {
    name: "Paint A Wave Function Collapse",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">
        Paint A Wave Function Collapse Description
      </p>
    ),
    cssId: "project-wfc",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: ["Python", "PyGame", "HTML", "CSS", "JavaScript", "WebAssembly"],
    thumbnailImgSrc: "/images/wfc-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EAB0QAAICAgMBAAAAAAAAAAAAAAECBAUDEQYHEgj/xAAUAQEAAAAAAAAAAAAAAAAAAAAG/8QAIBEAAgEDBAMAAAAAAAAAAAAAAQIRAwQSBSExUQAGQf/aAAwDAQACEQMRAD8Ae+wupOJfOcXjsCMZV5PkU8a1ubadkTHknWG8pEjyieE8qqoo0SAuyWOyT1Ku9TS6V9dAVHByWQBhkQsKQJ45JmT1tCTXb631v2U1bagturNgqqWYKpPbGWJIlpgE/ANvP//Z",
    previewImgSrcList: [
      "/images/wfc-preview-1.png",
      "/images/wfc-preview-2.png",
      "/images/wfc-preview-gif.gif",
    ],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EACAQAAIBAwQDAAAAAAAAAAAAAAECAwQFEQASEyExQVH/xAAVAQEBAAAAAAAAAAAAAAAAAAACBf/EACERAAEDBAEFAAAAAAAAAAAAAAECBBEAAwUhMRIycdHw/9oADAMBAAIRAxEAPwBStdwqKi2ytIkBYJxOTSxncAgPtcqevIOR91MxmHa4hsls21bSSY57iSdneyeZpI6bACYke/Hxr//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EABwQAAIDAAMBAAAAAAAAAAAAAAECAwQGABESBf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAIREAAgAEBwEAAAAAAAAAAAAAAQIDBRExAAQSISJBUUL/2gAMAwEAAhEDEQA/AGz6OfzGFhpUcnnYKxqUSstmZ3mntTBPL2ZJHJYyureSR0AAAAAOuGh5TRpLsXZa8moTQ3A8Fth5ijMpnFmcwfNxEVS3yihFA6AAsBfsk7k1OP/Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAA//EACIQAAEDAwMFAAAAAAAAAAAAAAIBAwQFBhEABwgSEyIxYf/EABQBAQAAAAAAAAAAAAAAAAAAAAb/xAAhEQEAAQQCAQUAAAAAAAAAAAABAgMREiEAMQYEBxYiQf/aAAwDAQACEQMRAD8ADm/a8mlbSuuDcMomhq0NkIIAARmsd1esAFMiS+l8lT4mgPldKXxinacu4G27odq7V/Vd8Ge5VSEvDo+mjTiJVi5/bNLSMVyxxOy0Rv2vP//Z",
    ],
    // cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
  },
  "screenshot-ocr": {
    name: "Screenshot OCR",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Screenshot OCR Description</p>
    ),
    cssId: "project-ocr",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["Python", "PyQt"],
    thumbnailImgSrc: "/images/screenshot-ocr-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB8QAAEDBQADAAAAAAAAAAAAAAECAxEEBQYHEgAhMf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIRABIx/9oADAMBAAIRAxEAPwBfcM1nqK6YWimv+rLLUJXTudpZt7LfQkg++CqSRMhQEn55bPMYszdMaTv/2Q==",
    previewImgSrcList: [
      "/images/screenshot-ocr-preview.png",
      "/images/screenshot-ocr-preview-gif.gif",
    ],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAECBQUAAAAAAAAAAAAAAAEDEQIEBQYHABMxQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAERJR/9oADAMBAAIRAxEAPwBdbVxphmespJCv4hoc0CgYoglT0EgWUHe2YncPy3mm+RYszaY2Z//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAECBQUAAAAAAAAAAAAAAAEDEQIEBQYHABMxQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAERJR/9oADAMBAAIRAxEAPwBdbVxphmespJCv4hoc0CgYoglT0EgWUHe2YncPy3mm+RYszaY2Z//Z",
    ],
    // cssGradient: "bg-gradient-to-r from-rose-600 to-red-600",
  },
  "file-opener": {
    name: "File Opener",
    shortDescription: "Short Description",
    fullDescription: <p className="text-stone-100">File Opener Description</p>,
    cssId: "project-file-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/file-opener-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB8QAAIBBAIDAAAAAAAAAAAAAAECBAMFESEGBwASFP/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAeEQACAQMFAAAAAAAAAAAAAAABAwIAESEEEkFxsf/aAAwDAQACEQMRAD8AVu38P6fulpl0H6M4iseRH+WpFex0aiIjZyVDqdkgHLe2xrHjVqXBgbE7ZA4Ixa3VFiFCBWReJ4Ofa//Z",
    previewImgSrcList: ["/images/file-opener-preview.png"],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAIBBAEFAAAAAAAAAAAAAAECBAMFBhEHABIUITH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAHxEAAgEDBQEAAAAAAAAAAAAAAQMCABEhBBIxQZGx/9oADAMBAAIRAxEAPwBU42JcM3KzTYz8BYcI9eP41SM9ioVEVG2SVDodEkb23d7+a6atS4MDYm0hwRi3lGaFbCsi4PRz9r//2Q==",
    ],
    // cssGradient: "bg-gradient-to-r from-orange-500 to-amber-400",
  },
  "link-opener": {
    name: "Link Opener",
    shortDescription:
      "Desktop GUI application to automate asd asd asd dsaadssadasd asdsadsad asd. asdsaddsad",
    fullDescription: <p className="text-stone-100">Link Opener Description</p>,
    cssId: "project-link-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/link-opener-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACIQAAECAwkAAAAAAAAAAAAAAAECAwUGCAAEBxMWITEyUf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAIBEAAAQGAwAAAAAAAAAAAAAAAAEEEgIDERNBURQxsf/aAAwDAQACEQMRAD8AVSHU60+PQ1Mms4FSa20+kOZumLoopHcp3b4JHtkVzZi+I4lBuM+65oJ+KmsWWkzWN+j/2Q==",
    previewImgSrcList: ["/images/link-opener-preview.png"],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACEQAAECBgIDAAAAAAAAAAAAAAEEEQIDBggSEwAFFhhB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAfEQACAQIHAAAAAAAAAAAAAAABAgQAMQMREyJBUWH/2gAMAwEAAhEDEQA/AFNTW826x9P496/UXoSyyqOVMJCZgEOWsnW7OT9filsZ7FpG4m+flqnMSK2DpMgK9cV//9k=",
    ],
    // cssGradient: "bg-gradient-to-r from-blue-400 to-fuchsia-800",
  },
};
