export const ProjectsInfo = {
  "price-performance-scraper": {
    name: "Price-Performance Scraper",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Price-Performance Scraper Description</p>
    ),
    cssId: "project-pps",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: [
      "Python",
      "Django",
      "HTML",
      "CSS",
      "TypeScript",
      "React",
      "Next.js",
      "PostgreSQL",
      "Docker",
    ],
    thumbnailImgSrc: "/images/pps-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB4QAAICAQUBAAAAAAAAAAAAAAIEAQMRBQYHEhMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwX/xAAhEQABBAEDBQAAAAAAAAAAAAABAgQRITEAElEDBRMiQf/aAAwDAQACEQMRAD8AOQLdk8wutO8ibc1Ft9dHXbKGF9a8q64oRCxUIr8pjAXdjP7mwSgcjjtMxw5eSFhSbKJ9R9JBxAsYqs3pW3a0Mel4t0gbuRYubJ5xr//Z",
    previewImgSrcList: [
      "/images/pps-preview-1.png",
      "/images/pps-preview-2.png",
      "/images/pps-preview-3.png",
      "/images/pps-preview-4.png",
      "/images/pps-preview-5.png",
    ],
    previewImgMainWidth: 392,
    previewImgMainHeight: 325,
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EACEQAAEEAgICAwAAAAAAAAAAAAIBAwQFBhEABxMUEiIx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQQF/8QAIBEAAgEEAgMBAAAAAAAAAAAAAQIRAAMEMSEiBhITBf/aAAwDAQACEQMRAD8AA+Q9d2vYV5Eq84tbPBfTyikopPhxsnPC1Njq97LxNyHFUxFEIGRXZiXy+i7TkWV5BkZy/ZALkIxHdoPq0QPYSJOzoEao/K8ZzsG2Ua3EuFJ6mGYSo6hZleRxxok0eMnyO8oslsaNqdMlhDnPMDKKYoK8gGooaiqbHet6X83zRtuHthiNih0+blTscV//2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQn/xAAgEAACAgEDBQAAAAAAAAAAAAABAwIEIQAFEQYxQlFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAdEQACAgIDAQAAAAAAAAAAAAABAgQRACEDQbGB/9oADAMBAAIRAxEAPwCVfV+6Xb24OU4ojGutUFCvTWoccA5EY5OT350nJM5ZgVnI7qgB4Bk8eIkRSq3vZssfSa+YJZDY2GRFmeJnwj7+aIGxePvP/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgn/xAAiEAACAAUDBQAAAAAAAAAAAAABAgADBAUhBgcSFDEyodH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EAB4RAAAGAwEBAAAAAAAAAAAAAAECBBEhMQADBRLR/9oADAMBAAIRAxEAPwCZ25di09Qa6FDaZDdO1tpZp5TGJ5tTh2zg+XrEXdIecZSJkIvraLtpubfDMl6SA46VpfOwJaKEHLThID9wi7AuSARnsGb7EOJn/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgn/xAAfEAEAAgAGAwAAAAAAAAAAAAABAgMABAUhMUEGEdH/xAAWAQEBAQAAAAAAAAAAAAAAAAADAQL/xAAfEQACAgEEAwAAAAAAAAAAAAABAgADIRESE5FRUmH/2gAMAwEAAhEDEQA/AJb+cTdVytGsWaLVXO0S2zLVQrgepMQIwANonAd9rjNt1l1hdjn4AB0NBDR+JAirgecns5MOEbEFruduW6X3B7ml529Z/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQn/xAAgEAACAgAGAwAAAAAAAAAAAAABAgMFAAQREyExBhJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAcEQACAgIDAAAAAAAAAAAAAAABAgARUWEDIfD/2gAMAwEAAhEDEQA/AJKeRXlHZ2G9lLRhlwF2458uxZetQSiqD0egODivIylurrfhJqpC4OoVLbRmVtuOAr7HQhGHHzTApcxWcT//2Q==",
    ],
    previewImgMenuWidthList: [59, 59, 59, 59, 59],
    previewImgMenuHeightList: [48, 48, 48, 48, 48],
    // cssGradient: "bg-gradient-to-r from-violet-500 via-rose-500 to-orange-600",
  },
  "pathfinding-race": {
    name: "Pathfinding Race",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Pathfinding Race Description</p>
    ),
    cssId: "project-pathfinding",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["HTML", "CSS", "JavaScript", "React"],
    thumbnailImgSrc: "/images/pathfinding-race-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EACAQAAICAQMFAAAAAAAAAAAAAAECAwQGBQcRABIhI0H/xAAVAQEBAAAAAAAAAAAAAAAAAAACBv/EACARAAIBAwUBAQAAAAAAAAAAAAECEQMEEgAFITEyBkH/2gAMAwEAAhEDEQA/AE3cDPsj2pzLTcX0d61mtZkpKstmv7oo5ZUR1DKQCe1/DEcgj7z0vldjsN2pM7AqAKxgR6p5EHryY5WJ5nLVbttlaXFKqkFWDMRiQFAFJXjEgmciecuj1+6//9k=",
    previewImgSrcList: [
      "/images/pathfinding-race-preview-1.png",
      "/images/pathfinding-race-preview-2.png",
      "/images/pathfinding-race-preview-3.png",
      "/images/pathfinding-race-preview-4.png",
      "/images/pathfinding-race-preview-gif.gif",
    ],
    previewImgMainWidth: 300,
    previewImgMainHeight: 299,
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAKAAoDAREAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIH/8QAJBAAAgIBAwMFAQAAAAAAAAAAAQMCBBEABSEGEkETFCIxUZH/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EACERAAECBQUBAAAAAAAAAAAAAAECAwAEITFBERMUUbEi/9oADAMBAAIRAxEAPwDe+jaqKHSVTbK9bbrtoe1XJjaoK4icT3AzhEjOYntzxwRIxJGgXUBxxRwYpZl1RmVmumppfJ77iblBbrbXR3FBE2SIMVKwcnxjj+aDfWxvq+MnJ7h2WU7xkfeB5B+mWMO67ukskYM2hRnEniXzH2POk3FK27wVMNoLy6C59h1yhRFtoFJQAZLA9MfupOZcc5C6m59imlUI4yKCw8j/2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAKAAoDAREAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQGB//EACUQAAICAQMDBAMAAAAAAAAAAAECAwQFAAYREiEiBxQxUSQzQ//EABUBAQEAAAAAAAAAAAAAAAAAAAUG/8QAJREAAgIBAwMEAwAAAAAAAAAAAQIDEQQAEiExQbEFBhMUI1GR/9oADAMBAAIRAxEAPwDTd0ZjM+l+3KdnGbRpZ6A4pp4naBo2idE7JKVQqwZkcD4J8SOQdC+3IfSfcOdkxLKY1hkKzFgRtBCndHvIEgBNMENLXSzWqlVwx6kYJndGmdRGArOpZmYPuYt+OgFIBFGyBVaqKDUM1RhzMtgxtbiWZkjgjKqWHVwPH476BzWxkzJFjXcoY0bIsWaNHkWOx6acAlxx8ReyvF/uuO1j+E6NuexYgxkLQTuhfGxdZRiOrhq4HP3wNIlm29dEzRx/O3A6nydOX7973035sv7W/ofs6k8l3+y/J6nzqkxkQYycdh41/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAKAAoDAREAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQGCP/EACMQAAICAgIBBAMAAAAAAAAAAAECAwQFBwYRAAgSISIUQWH/xAAWAQEBAQAAAAAAAAAAAAAAAAAFAwT/xAAeEQACAQQDAQAAAAAAAAAAAAABAgADEiFBERNxMv/aAAwDAQACEQMRAD8AofTt6aNU5vUXD8xkdG4XIm7x2hLYvW8X7zM7RqXZvr9iT32fBq9UkkY3HCtzEkbmL9v41MRtrlGJxNP8erV5FdhrV4a4VIo1ndVVR+gAAAP55IlOciWW60Zgo7Y2niVqYrFbL5BWqwuixVq+ZnSNFCdABQ/QA8uwHI8mV/s+xG9duXrs127blmmmlZ5ppZCzOxPZYk/JJPySfC6rN2NnZidJV6lxoT//2Q==",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAKAAoDAREAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwIE/8QAJhAAAgECBQIHAAAAAAAAAAAAAQIDAAQFBgcSIQgxERMyM0JRYf/EABYBAQEBAAAAAAAAAAAAAAAAAAUEA//EAB0RAAICAgMBAAAAAAAAAAAAAAECAAMhQRESE3H/2gAMAwEAAhEDEQA/ABPR3R/pyzDpjY4tnTqDssHxuZnSTBbm2hDRqCwTllBbcApH3u79qNsySeOYs/VnJJ3CWWG4MrGWFwxY7gtuPAGpLGQOcblVXfzXOhNcYEslo8o3HzE5bk+g1uWYEcHUnsVe5xsyLuaY3UhMre4fl+0bYT6H7EK1HmMan//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAKAAoDAREAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFB//EACgQAAEDAwEGBwAAAAAAAAAAAAECAwQABSESBgcREyJhMUFCUVNxsf/EABcBAQEBAQAAAAAAAAAAAAAAAAUGAwT/xAAmEQABAgUCBgMAAAAAAAAAAAABAgMABBEhQSJhExQxQlFxseHw/9oADAMBAAIRAxEAPwDa93T9vj2GDa5mzsaW67EVyUrt6W1urSE9A1A6jpPtkgqA05oN9AW8q9QdrfviKeYedVMruaEm1Scmt819QzLh296W66zMbbQpxRQ25Z1NqSCcAp9J7eXhQ7xlg8oBGTn6hyWXMcsjXgefHuBsXOmt2ixpbmOpAJcADhHBfKR1feTnvXW8tYFjGa2WeYXpHdgRLuWbjI4/Ov8ATUy+67x1aj1Od4bl2WuAjSOgxtH/2Q==",
    ],
    previewImgMenuWidthList: [50, 50, 50, 50, 50],
    previewImgMenuHeightList: [50, 50, 50, 50, 50],
    // cssGradient: "bg-gradient-to-r from-yellow-300 to-pink-600",
  },
  "paint-a-wave-function-collapse": {
    name: "Paint A Wave Function Collapse",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">
        Paint A Wave Function Collapse Description
      </p>
    ),
    cssId: "project-wfc",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: ["Python", "PyGame", "HTML", "CSS", "JavaScript", "WebAssembly"],
    thumbnailImgSrc: "/images/wfc-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EAB0QAAICAgMBAAAAAAAAAAAAAAECBAUDEQYHEgj/xAAUAQEAAAAAAAAAAAAAAAAAAAAG/8QAIBEAAgEDBAMAAAAAAAAAAAAAAQIRAwQSBSExUQAGQf/aAAwDAQACEQMRAD8Ae+wupOJfOcXjsCMZV5PkU8a1ubadkTHknWG8pEjyieE8qqoo0SAuyWOyT1Ku9TS6V9dAVHByWQBhkQsKQJ45JmT1tCTXb631v2U1bagturNgqqWYKpPbGWJIlpgE/ANvP//Z",
    previewImgSrcList: [
      "/images/wfc-preview-1.png",
      "/images/wfc-preview-2.png",
      "/images/wfc-preview-gif.gif",
    ],
    previewImgMainWidth: 390,
    previewImgMainHeight: 317,
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAf/xAAhEAADAAEEAQUAAAAAAAAAAAABAgMFAAQRMSEGEiJScf/EABYBAQEBAAAAAAAAAAAAAAAAAAYBAv/EACYRAQACAAMGBwAAAAAAAAAAAAECEQADIQQFEhMxQQYiMmGh4fD/2gAMAwEAAhEDEQA/AKvhsjtbrO1fTeKq8ZIKbfIbYKrfHp0KKeevP4TotuPcUvD+7ZbLknGMpT82ZKSyUfVI0LNCqA6NuLkR5UQk99aV6trbep2AqgNOuBWlhWs7U4gxYloThErM/UH3+QOudLGML0l8feNz5PG8Np+9sf/Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAIAAoDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAQf/xAAfEAADAQABBQEBAAAAAAAAAAABAgMEBQAGBxEhEhT/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EACARAQABBAMAAwEAAAAAAAAAAAECBBESIQADBQYUQYH/2gAMAwEAAhEDEQA/ALHDxR4+8eds8PlfRp5zmdOaV+7d+85sv9W5G/cjOUncKk5hFVnAZiPbEnoqFNVd3STrSPZOEsoABjbQE7Cr+rreixyh+Ser5/r+w1NBT/X6jUY5Skg6kyV2y2pbH8A4au6sddVK2q03ahLzVZkKff0Ain310pjHgcpuTZv/AAOf/9k=",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAADAAkDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQj/xAAjEAABAgUDBQAAAAAAAAAAAAACAQMABAUREggTYRRCUZLR/8QAFgEBAQEAAAAAAAAAAAAAAAAABgcI/8QAIxEAAQEIAQUAAAAAAAAAAAAAAREAAgMEBhIxYfAhIjJCkf/aAAwDAQACEQMRAD8AR1cUWnhp+r1TAXUdEJdoUSZcwQeqa7Msb82vzA+poMOHSkR13ADoHU4DwTmWKV9MRBRszLBLOw+IVQ8PZLk0qaaL9kPJ+6/YjNo4S2b7Bv6W/9k=",
    ],
    previewImgMenuWidthList: [59, 59, 70],
    previewImgMenuHeightList: [48, 48, 48],
    // cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
  },
  "screenshot-ocr": {
    name: "Screenshot OCR",
    shortDescription: "Short Description",
    fullDescription: (
      <p className="text-stone-100">Screenshot OCR Description</p>
    ),
    cssId: "project-ocr",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["Python", "PyQt"],
    thumbnailImgSrc: "/images/screenshot-ocr-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB8QAAEDBQADAAAAAAAAAAAAAAECAxEEBQYHEgAhMf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIRABIx/9oADAMBAAIRAxEAPwBfcM1nqK6YWimv+rLLUJXTudpZt7LfQkg++CqSRMhQEn55bPMYszdMaTv/2Q==",
    previewImgSrcList: [
      "/images/screenshot-ocr-preview.png",
      "/images/screenshot-ocr-preview-gif.gif",
    ],
    previewImgMainWidth: 406,
    previewImgMainHeight: 245,
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAECBQUAAAAAAAAAAAAAAAEDEQIEBQYHABMxQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAERJR/9oADAMBAAIRAxEAPwBdbVxphmespJCv4hoc0CgYoglT0EgWUHe2YncPy3mm+RYszaY2Z//Z",
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAECBQUAAAAAAAAAAAAAAAEDEQIEBQYHABMxQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAERJR/9oADAMBAAIRAxEAPwBdbVxphmespJCv4hoc0CgYoglT0EgWUHe2YncPy3mm+RYszaY2Z//Z",
    ],
    previewImgMenuWidthList: [85, 85],
    previewImgMenuHeightList: [50, 50],
    // cssGradient: "bg-gradient-to-r from-rose-600 to-red-600",
  },
  "file-opener": {
    name: "File Opener",
    shortDescription: "Short Description",
    fullDescription: <p className="text-stone-100">File Opener Description</p>,
    cssId: "project-file-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/file-opener-thumbnail.png",
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EAB8QAAIBBAIDAAAAAAAAAAAAAAECBAMFESEGBwASFP/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAeEQACAQMFAAAAAAAAAAAAAAABAwIAESEEEkFxsf/aAAwDAQACEQMRAD8AVu38P6fulpl0H6M4iseRH+WpFex0aiIjZyVDqdkgHLe2xrHjVqXBgbE7ZA4Ixa3VFiFCBWReJ4Ofa//Z",
    previewImgSrcList: ["/images/file-opener-preview.png"],
    previewImgMainWidth: 407,
    previewImgMainHeight: 256,
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACAQAAIBBAEFAAAAAAAAAAAAAAECBAMFBhEHABIUITH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAHxEAAgEDBQEAAAAAAAAAAAAAAQMCABEhBBIxQZGx/9oADAMBAAIRAxEAPwBU42JcM3KzTYz8BYcI9eP41SM9ioVEVG2SVDodEkb23d7+a6atS4MDYm0hwRi3lGaFbCsi4PRz9r//2Q==",
    ],
    previewImgMenuWidthList: [81],
    previewImgMenuHeightList: [50],
    // cssGradient: "bg-gradient-to-r from-orange-500 to-amber-400",
  },
  "link-opener": {
    name: "Link Opener",
    shortDescription:
      "Desktop GUI application to automate asd asd asd dsaadssadasd asdsadsad asd. asdsaddsad",
    fullDescription: <p className="text-stone-100">Link Opener Description</p>,
    cssId: "project-link-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/link-opener-thumbnail.png",
    previewImgMainWidth: 402,
    previewImgMainHeight: 227,
    thumbnailBase64Data:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACIQAAECAwkAAAAAAAAAAAAAAAECAwUGCAAEBxMWITEyUf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAIBEAAAQGAwAAAAAAAAAAAAAAAAEEEgIDERNBURQxsf/aAAwDAQACEQMRAD8AVSHU60+PQ1Mms4FSa20+kOZumLoopHcp3b4JHtkVzZi+I4lBuM+65oJ+KmsWWkzWN+j/2Q==",
    previewImgSrcList: ["/images/link-opener-preview.png"],
    previewImgBase64DataList: [
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAFAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EACEQAAECBgIDAAAAAAAAAAAAAAEEEQIDBggSEwAFFhhB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAfEQACAQIHAAAAAAAAAAAAAAABAgQAMQMREyJBUWH/2gAMAwEAAhEDEQA/AFNTW826x9P496/UXoSyyqOVMJCZgEOWsnW7OT9filsZ7FpG4m+flqnMSK2DpMgK9cV//9k=",
    ],
    previewImgMenuWidthList: [90],
    previewImgMenuHeightList: [50],
    // cssGradient: "bg-gradient-to-r from-blue-400 to-fuchsia-800",
  },
};
