export const ProjectsInfo = {
  "price-performance-scraper": {
    name: "Price-Performance Scraper",
    shortDescription: "Short Description",
    fullDescription: "Price-Performance Scraper Description",
    cssId: "project-pps",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: [
      "Python",
      "Django",
      "HTML",
      "CSS",
      "TypeScript",
      "React",
      "Next.js",
      "PostgreSQL",
      "Docker",
    ],
    thumbnailImgSrc: "/images/pps-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-violet-500 via-rose-500 to-orange-600",
  },
  "pathfinding-race": {
    name: "Pathfinding Race",
    shortDescription: "Short Description",
    fullDescription: "Pathfinding Race Description",
    cssId: "project-pathfinding",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["HTML", "CSS", "JavaScript", "React"],
    thumbnailImgSrc: "/images/pathfinding-race-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-yellow-300 to-pink-600",
  },
  "paint-a-wave-function-collapse": {
    name: "Paint A Wave Function Collapse",
    shortDescription: "Short Description",
    fullDescription: "Paint A Wave Function Collapse Description",
    cssId: "project-wfc",
    cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
    techStack: ["Python", "PyGame", "HTML", "CSS", "JavaScript", "WebAssembly"],
    thumbnailImgSrc: "/images/wfc-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-rose-600 via-red-500 to-orange-400",
  },
  "screenshot-ocr": {
    name: "Screenshot OCR",
    shortDescription: "Short Description",
    fullDescription: "Screenshot OCR Description",
    cssId: "project-ocr",
    cssGradient: "bg-gradient-to-r from-rose-600 to-amber-400",
    techStack: ["Python", "PyQt"],
    thumbnailImgSrc: "/images/screenshot-ocr-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-rose-600 to-red-600",
  },
  "file-opener": {
    name: "File Opener",
    shortDescription: "Short Description",
    fullDescription: "File Opener Description",
    cssId: "project-file-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/file-opener-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-orange-500 to-amber-400",
  },
  "link-opener": {
    name: "Link Opener",
    shortDescription: "Desktop GUI application to automate asd asd asd dsaadssadasd asdsadsad asd. asdsaddsad",
    fullDescription: "Link Opener Description",
    cssId: "project-link-opener",
    cssGradient: "bg-gradient-to-r from-rose-600 to-yellow-400",
    techStack: ["Python", "Tkinter"],
    thumbnailImgSrc: "/images/link-opener-thumbnail.png",
    // cssGradient: "bg-gradient-to-r from-blue-400 to-fuchsia-800",
  },
};
